
import { LanguageStrings } from './types';

export const TRANSLATIONS: Record<'en' | 'ar', LanguageStrings> = {
  en: {
    title: 'Medicine Quiz Pro',
    uploadFiles: 'Upload Medical Content',
    generateQuiz: 'AI Question Generator',
    subjects: 'Subjects',
    chapters: 'Chapters',
    stats: 'Statistics',
    leaderboard: 'Leaderboard',
    difficulty: 'Complexity',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    veryHard: 'Expert/Very Hard',
    mcq: 'MCQ',
    tf: 'True/False',
    mix: 'Mix Mode',
    questionCount: 'Questions Count',
    startQuiz: 'Start Session',
    results: 'Medical Report',
    share: 'Share Quiz',
    score: 'Final Score',
    time: 'Time Taken',
    translate: 'Translate To',
    toArabic: 'Arabic',
    toEnglish: 'English',
    original: 'Original',
    back: 'Back',
    login: 'Sign in with Google',
    logout: 'Sign Out',
    welcome: 'Welcome, Dr.',
    importQuiz: 'Import Shared Quiz',
    copySuccess: 'Link copied to clipboard!',
    next: 'Next',
    finish: 'Finish'
  },
  ar: {
    title: 'ميديكال كويز برو',
    uploadFiles: 'رفع المحتوى الطبي',
    generateQuiz: 'توليد الأسئلة بالذكاء الاصطناعي',
    subjects: 'المواد',
    chapters: 'الفصول',
    stats: 'الإحصائيات',
    leaderboard: 'لوحة المتصدرين',
    difficulty: 'مستوى الصعوبة',
    easy: 'سهل',
    medium: 'متوسط',
    hard: 'صعب',
    veryHard: 'صعب جداً / خبير',
    mcq: 'اختيار من متعدد',
    tf: 'صح وخطأ',
    mix: 'مزيج',
    questionCount: 'عدد الأسئلة',
    startQuiz: 'بدء الاختبار',
    results: 'تقرير النتائج',
    share: 'مشاركة الاختبار',
    score: 'النتيجة',
    time: 'الوقت المستغرق',
    translate: 'ترجمة الأسئلة لـ',
    toArabic: 'العربية',
    toEnglish: 'الإنجليزية',
    original: 'لغة المصدر',
    back: 'رجوع',
    login: 'تسجيل الدخول بجوجل',
    logout: 'تسجيل خروج',
    welcome: 'مرحباً دكتور',
    importQuiz: 'استيراد اختبار مشترك',
    copySuccess: 'تم نسخ الرابط بنجاح!',
    next: 'التالي',
    finish: 'إنهاء'
  }
};
