
import { LanguageStrings } from './types';

export const TRANSLATIONS: Record<'en' | 'ar', LanguageStrings> = {
  en: {
    title: 'Medicine Quiz',
    uploadFiles: 'Upload Files (PDF/Text)',
    generateQuiz: 'AI Question Generator',
    subjects: 'Categories',
    chapters: 'Chapters',
    stats: 'Statistics',
    leaderboard: 'Leaderboard',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    veryHard: 'Very Hard',
    mcq: 'MCQ',
    tf: 'True/False',
    mix: 'Mix Mode',
    questionCount: 'Questions Count',
    startQuiz: 'Start Session',
    results: 'Results Report',
    share: 'Share Quiz',
    score: 'Final Score',
    time: 'Time Taken',
    translate: 'Translate To',
    toArabic: 'Arabic',
    toEnglish: 'English',
    original: 'Original',
    back: 'Back',
    home: 'Home',
    login: 'Sign in / Create Account',
    logout: 'Sign Out',
    welcome: 'Welcome, ',
    importQuiz: 'Import Shared Quiz',
    copySuccess: 'Link copied to clipboard!',
    clearCache: 'Clear All Data',
    exportData: 'Export All Data',
    importData: 'Import All Data',
    explanation: 'Explanation',
    modelAnswer: 'Model Answer',
    quizTitle: 'Quiz Title',
    passingScore: 'Passing Score (%)',
    pass: 'Passed',
    fail: 'Failed',
    rename: 'Rename',
    delete: 'Delete',
    addCategory: 'Add Category',
    categoryName: 'Category Name',
    uncategorized: 'Uncategorized',
    mcqRatio: 'MCQ Ratio (%)',
    next: 'Next',
    finish: 'Finish',
    multipleSelect: 'Multiple Selection',
    selectRequired: 'answers required',
    checkAnswer: 'Verify Answer',
    shortAnswer: 'Short Answer',
    practical: 'Practical (Images)',
    writeAnswer: 'Write your answer here...',
    practiceTitle: 'Practical Exam',
    switchToMCQ: 'Switch to Multiple Choice',
    switchToType: 'Switch to Type Answer',
  },
  ar: {
    title: 'Medicine Quiz',
    uploadFiles: 'رفع الملفات (PDF/Text)',
    generateQuiz: 'توليد الأسئلة بالذكاء الاصطناعي',
    subjects: 'التصنيفات',
    chapters: 'الفصول',
    stats: 'الإحصائيات',
    leaderboard: 'لوحة المتصدرين',
    difficulty: 'مستوى الصعوبة',
    easy: 'سهل',
    medium: 'متوسط',
    hard: 'صعب',
    veryHard: 'صعب جداً',
    mcq: 'اختيار من متعدد',
    tf: 'صح وخطأ',
    mix: 'مزيج',
    questionCount: 'عدد الأسئلة',
    startQuiz: 'بدء الاختبار',
    results: 'تقرير النتائج',
    share: 'مشاركة الاختبار',
    score: 'النتيجة',
    time: 'الوقت المستغرق',
    translate: 'ترجمة الأسئلة لـ',
    toArabic: 'العربية',
    toEnglish: 'الإنجليزية',
    original: 'لغة المصدر',
    back: 'رجوع',
    home: 'الرئيسية',
    login: 'دخول / إنشاء حساب',
    logout: 'تسجيل خروج',
    welcome: 'مرحباً، ',
    importQuiz: 'استيراد اختبار مشترك',
    copySuccess: 'تم نسخ الرابط بنجاح!',
    clearCache: 'مسح كافة البيانات',
    exportData: 'تصدير كافة البيانات',
    importData: 'استيراد كافة البيانات',
    explanation: 'الشرح والتوضيح',
    modelAnswer: 'الإجابة النموذجية',
    quizTitle: 'عنوان الاختبار',
    passingScore: 'درجة النجاح (%)',
    pass: 'ناجح',
    fail: 'راسب',
    rename: 'تغيير الاسم',
    delete: 'حذف',
    addCategory: 'إضافة قسم',
    categoryName: 'اسم القسم',
    uncategorized: 'بدون قسم',
    mcqRatio: 'نسبة الاختيار من متعدد (%)',
    next: 'التالي',
    finish: 'إنهاء',
    multipleSelect: 'اختيارات متعددة',
    selectRequired: 'إجابات مطلوبة',
    checkAnswer: 'تحقق من الإجابة',
    shortAnswer: 'إجابة قصيرة',
    practical: 'عملي (صور)',
    writeAnswer: 'اكتب إجابتك هنا...',
    practiceTitle: 'امتحان عملي',
    switchToMCQ: 'تحويل لاختيار من متعدد',
    switchToType: 'تحويل لكتابة الإجابة',
  }
};
